!!AA_SEQUENCE 1.0
ORF_4_7


orf_4_7.pep  Length: 1433  October 29, 1999 14:30  Type: P  Check: 9031  ..

       1  MWGQMRNRNW RSRALCTVVA TSLLALGGPL LSATAAGGPN IAVGDATAAS 

      51  SSHGEYGAAN ITDGNQGTYW QSGGGSLPQW VQTDLGATER IDEVVLRLPA 

     101  GWESRDQTLS VQGSADGTGF STLKTSATYA FDPGSGNTVT IAFPATQTRF 

     151  VRVDITANTG WQAAQLSELE VHAAGESSVD LAAGRRLTAS SSTGAYTPGN 

     201  GNDGNRATYW ESANNALPQW LQADLGSARR VNRVVLRLPD GWPARSQTLK 

     251  IQASDNGSDF TDLTAAKAYT FDAAGGQSAT VTFDAATARY VRVLVTANTG 

     301  QPAAQISELE VYGPETGDTQ APTTPANLAF TEPATGQIRL TWNESSDDTA 

     351  VTGYDVYANG DLLTSVAGDV TTYTDTRPAG TTVTYHVRAK DAAGNQSGDS 

     401  NSVTRRADTG DTQAPTAPSN LALTEPVPGQ VKLTWTASTD DRGVTGYDVY 

     451  ADNKLRKSVA GNVTTYTDTQ PASANVTYFV RAKDAAGNES GDSNSVFRGG 

     501  TMDGSNLAVG KPITASSHIH TYVAENANDN STSTYWEGAA GGYPNTLTLK 

     551  LGANADVDSV VLKLNPDAGW SRRTQHIEVL GRAQDASGLT SLVAAKDYVF 

     601  DPASGGNSVT IPVGERAADV QLKVTSNTGA TAGQVAEFQV IGTPAPNPDL 

     651  EVTGLTTSPG SPVESDEITV SATVRNSGAA DAPAGKVAVR LGDTKVATAD 

     701  VPALEAGAQR TVSASLGARE AGSYELSAVA DEANEIIEQN ETNNTYTRPD 

     751  PLVVKPVQSS DLVAAAVTTS PSSPAAGDDV TFRVALRNQG TQDSAGGGHP 

     801  VTLALVDSKG DTVKTLTGTH SGVIAAGSTA PAVSLGTWKA ANGSYSLKVT 

     851  VADDANELPV KRENNTSTQP LFVGRGANMP YDMYEAEDGT VGGGATVVGP 

     901  NRTIGDIAGE ASGRKAVHLD RTGEYVEFTT KADTNTLVTR FSIPDAPGGG 

     951  GIDATLDVYV DGVMKKALPL TSKYAWLYGA EASPGNSPGA GAPRHIYDEA 

    1001  HIMLGETVPA GSTIRLQKDA ANTSDYAIDF VNLEQVSATA NPDPAAYAVP 

    1051  AGFTHQDVQN ALDKVRMDTS GKLVGVYLPP GDYQTSSKFQ VYGKAVKVVG 

    1101  AGPWFTKFHA PTTQDNTDIG FRAEASAKGS TFANFAYFGN YTSRIDGPGK 

    1151  VFDFSNTSDI VIDNIWNEHM VCLYWGANTD RMTIRNSRIR NMFADGINMT 

    1201  NGSTDNLVSN NDARATGDDS FALFSAIDAG GADMKNNLYE NLTTTLTWRA 

    1251  AGLAVYGGYN NTFRNIHIAD TLVYSGITIS SLDFGYPMNG FGTDPTTFEN 

    1301  VSIVRAGGHF WGGQTFPGIW VFSASKVFQG IRVNNVDIVD PTYSGIMFQT 

    1351  NYVGGQPQFP IKDTVFTDVS VTGAHKSGDE FDAKSGFGLW ANEMPESGQG 

    1401  PAVGEVTFNG LTLGDNAVDI RNTTSTFKII RKP

