name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy static site to S3 bucket
      run: |
        aws s3 sync ./public_html/ s3://tcoffee.org --delete --exclude "Packages/Archives/*"
        aws s3 sync ./public_html/Packages/Binaries/plugins/ s3://tcoffee-packages/Binaries/plugins/ --delete
